tower:
  appName: "${TOWER_APP_NAME:Nextflow Tower}"
  serverUrl: "${TOWER_SERVER_URL:`http://localhost:8000`}"
  contactEmail: "${TOWER_CONTACT_EMAIL:hello@foo.com}"
---
micronaut:
  application:
    name: tower-backend
    instance:
      id: ${random.shortuuid}
  server:
    port: ${MICRONAUT_PORT:8080}
    netty:
  caches:
    rate-limiter:
      expire-after-access: 10m
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
    token:
      jwt:
        enabled: true
        bearer:
          enabled: false
        cookie:
          enabled: true
          loginSuccessTargetUrl: "/auth?success=true"
          loginFailureTargetUrl: "/auth?success=false"
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
        generator:
          access-token-expiration: 86400
---
jackson:
  serialization:
    writeDatesAsTimestamps: false
  deserialization:
    adjustDatesToContextTimeZone: false
  serialization-inclusion: ALWAYS
# ^^^^^^
# Use this to avoid empty lists are stripped
# See com.fasterxml.jackson.annotation.JsonInclude.Include.*
#
---
dataSource:
  pooled: true
  dbCreate: "${TOWER_DB_CREATE:`update`}"
  url: "${TOWER_DB_URL:`jdbc:h2:file:./.db/h2/tower`}"
  driverClassName: "${TOWER_DB_DRIVER:`org.h2.Driver`}"
  username: "${TOWER_DB_USER:`sa`}"
  password: "${TOWER_DB_PASSWORD:``}"
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
  dialect: "${TOWER_DB_DIALECT:org.hibernate.dialect.H2Dialect}"
  naming_strategy: io.seqera.util.H8NamingStrategy
grails:
  gorm:
    failOnError: false
---
live:
  buffer:
    time: 5s
    count: 100
    heartbeat: 50s
